#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Project Context Builder v2 - GUI version.

Uses the original collector/reader from project_context_builder.py and adds:
- configurable file categories;
- configurable excluded folders;
- max file size;
- save path;
- clipboard copy;
- logging and statistics.
"""

from __future__ import annotations

import os
import platform
import subprocess
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk
from tkinter.scrolledtext import ScrolledText

import project_context_builder as core

APP_TITLE = "Project Context Builder"

CODE_EXTENSIONS = {
    ".py", ".pyw", ".pyi", ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx",
    ".html", ".htm", ".css", ".scss", ".sass", ".less", ".vue", ".svelte",
    ".java", ".kt", ".kts", ".groovy", ".c", ".h", ".cc", ".cpp", ".cxx",
    ".hpp", ".hh", ".cs", ".go", ".rs", ".php", ".phtml", ".rb", ".rake",
    ".pl", ".pm", ".swift", ".m", ".mm", ".sh", ".bash", ".zsh", ".fish",
    ".ps1", ".bat", ".cmd", ".sql",
}
CONFIG_EXTENSIONS = {
    ".json", ".jsonl", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
    ".properties", ".xml", ".env",
}
TEXT_EXTENSIONS = {".txt", ".md", ".markdown", ".rst", ".adoc", ".log", ".csv"}
DOCUMENT_NAMES = {"README", "README.md", "README.txt", "LICENSE", "LICENSE.txt"}
OUTPUT_NAMES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "Pipfile.lock"}
SPECIAL_CODE_NAMES = {"Dockerfile", "Makefile", "CMakeLists.txt", "Procfile"}

QUICK_EXTENSIONS = (".css", ".html", ".js", ".txt", ".py", ".json", ".md")


def category(path: Path) -> str | None:
    name = path.name
    suffix = path.suffix.lower()
    if name in SPECIAL_CODE_NAMES or suffix in CODE_EXTENSIONS:
        return "code"
    if suffix in CONFIG_EXTENSIONS:
        return "config"
    if name in DOCUMENT_NAMES:
        return "document"
    if name in OUTPUT_NAMES:
        return "output"
    if suffix in TEXT_EXTENSIONS:
        return "text"
    if core.is_probably_text_file(path):
        return "text"
    return None


def parse_exclusions(text: str) -> set[str]:
    result = set()
    for item in text.replace(";", ",").replace("\n", ",").split(","):
        item = item.strip().lower()
        if item:
            result.add(item)
    return result


def parse_extensions(text: str) -> set[str]:
    """Парсит строку с расширениями: 'css, .html js .txt' -> {'.css', '.html', '.js', '.txt'}."""
    result: set[str] = set()
    normalized = (
        text.replace(";", ",")
            .replace("\n", ",")
            .replace("\t", ",")
            .replace(" ", ",")
    )
    for item in normalized.split(","):
        item = item.strip().lower()
        if not item:
            continue
        if not item.startswith("."):
            item = "." + item
        result.add(item)
    return result


def build_context(root: Path, vars_: dict, max_mb: float, ignored: set[str],
                  ext_filter: set[str] | None = None, ext_exclude: bool = False):
    entries = core.collect_all_paths(root)
    entries = []

    def walk(cur: Path):
        try:
            children = sorted(cur.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
        except OSError:
            return
        for p in children:
            if p.is_dir():
                if p.name.lower() in ignored:
                    continue
                entries.append(p)
                walk(p)
            else:
                entries.append(p)
    walk(root)

    files = [p for p in entries if p.is_file()]
    enabled = {k: vars_[k].get() for k in ("code", "config", "text", "document", "output")}

    if ext_filter:
        if ext_exclude:
            # Режим «исключить эти расширения» — берём всё, кроме них.
            selected = [
                (p, category(p) or "text")
                for p in files
                if p.suffix.lower() not in ext_filter
            ]
        else:
            # Режим «только эти расширения» — категории игнорируем.
            selected = [
                (p, category(p) or "text")
                for p in files
                if p.suffix.lower() in ext_filter
            ]
    else:
        selected = [(p, category(p)) for p in files]
        selected = [(p, c) for p, c in selected if c and enabled.get(c, False)]

    max_bytes = max(1, int(max_mb * 1024 * 1024))

    parts = [
        "# PROJECT CONTEXT",
        "",
        "Generated by Project Context Builder.",
        f"Project root: {root.resolve()}",
    ]

    if vars_["tree"].get():
        tree = core.build_tree_text(root, entries)
        parts += ["", "#" * 110, "# FULL DIRECTORY TREE", "#" * 110, "", tree]

    parts += ["", "#" * 110, "# FILE CONTENTS", "#" * 110]

    included = 0
    skipped = []
    for p, c in sorted(selected, key=lambda x: x[0].relative_to(root).as_posix().lower()):
        rel = p.relative_to(root)
        text, error = core.read_text_file(p)
        # core's reader uses 2 MB fixed limit, so handle the user limit directly here.
        try:
            size = p.stat().st_size
        except OSError as exc:
            skipped.append((rel.as_posix(), str(exc)))
            continue
        if size > max_bytes:
            skipped.append((rel.as_posix(), f"слишком большой файл ({core.format_size(size)})"))
            continue
        if error and text is None:
            skipped.append((rel.as_posix(), error))
            continue
        if text is None:
            skipped.append((rel.as_posix(), "ошибка чтения"))
            continue
        if not vars_["empty"].get() and not text.strip():
            skipped.append((rel.as_posix(), "пустой файл"))
            continue
        rels = rel.as_posix()
        parts += [
            "", "=" * 110,
            f"FILE: {rels}", f"TYPE: {c}",
            "=" * 110,
            f"--- BEGIN FILE: {rels} ---",
            text.rstrip(),
            f"--- END FILE: {rels} ---",
            "=" * 110,
        ]
        included += 1

    parts += [
        "", "#" * 110, "# COLLECTION SUMMARY", "#" * 110,
        f"Total entries in tree: {len(entries)}",
        f"Total files: {len(files)}",
        f"Selected files: {len(selected)}",
        f"Included contents: {included}",
        f"Skipped: {len(skipped)}",
    ]
    if ext_filter:
        mode = "EXCLUDE" if ext_exclude else "INCLUDE only"
        parts.append(f"Extension filter ({mode}): {', '.join(sorted(ext_filter))}")
    if skipped:
        parts += ["", "Skipped files:"]
        parts += [f"- {name} -> {reason}" for name, reason in skipped]

    output = "\n".join(parts)
    stats = {
        "entries": len(entries), "files": len(files), "selected": len(selected),
        "included": included, "skipped": skipped,
        "size": len(output.encode("utf-8")),
    }
    return output, stats


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(APP_TITLE)
        self.geometry("1050x780")
        self.minsize(900, 700)
        self.context = ""
        self.root_var = tk.StringVar()
        self.output_var = tk.StringVar()
        self.max_var = tk.StringVar(value="2")
        self.tree_var = tk.BooleanVar(value=True)
        self.code_var = tk.BooleanVar(value=True)
        self.config_var = tk.BooleanVar(value=True)
        self.text_var = tk.BooleanVar(value=True)
        self.doc_var = tk.BooleanVar(value=True)
        self.output_files_var = tk.BooleanVar(value=False)
        self.empty_var = tk.BooleanVar(value=False)
        self.exclude_var = tk.StringVar(value=", ".join(sorted(core.DEFAULT_IGNORED_DIRS)))
        self.ext_filter_var = tk.StringVar(value="")
        self.ext_exclude_var = tk.BooleanVar(value=False)
        self.status_var = tk.StringVar(value="Выберите каталог проекта.")
        self.stats_var = tk.StringVar(value="Статистика: —")
        self.setup_ui()

    def setup_ui(self):
        # Внешний контейнер с вертикальной прокруткой
        outer = ttk.Frame(self)
        outer.pack(fill="both", expand=True)

        self.canvas = tk.Canvas(outer, highlightthickness=0)
        vsb = ttk.Scrollbar(outer, orient="vertical", command=self.canvas.yview)
        self.canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        self.canvas.pack(side="left", fill="both", expand=True)

        frame = ttk.Frame(self.canvas, padding=15)
        self._canvas_window = self.canvas.create_window(
            (0, 0), window=frame, anchor="nw"
        )

        def _on_frame_configure(_event):
            self.canvas.configure(scrollregion=self.canvas.bbox("all"))

        def _on_canvas_configure(event):
            self.canvas.itemconfigure(self._canvas_window, width=event.width)

        frame.bind("<Configure>", _on_frame_configure)
        self.canvas.bind("<Configure>", _on_canvas_configure)

        def _on_mousewheel(event):
            # Не перехватываем колесо, если курсор над текстовым виджетом (журнал).
            widget = self.winfo_containing(event.x_root, event.y_root)
            w = widget
            while w is not None:
                if isinstance(w, tk.Text):
                    return
                w = w.master
            self.canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        self.bind_all("<MouseWheel>", _on_mousewheel)

        # ---- Само содержимое ----
        ttk.Label(frame, text="Project Context Builder", font=("Segoe UI", 17, "bold")).pack(anchor="w")
        ttk.Label(frame, text="Настройте состав контекста и одним кликом соберите проект для ChatGPT.").pack(anchor="w", pady=(2, 12))

        g = ttk.LabelFrame(frame, text="1. Проект", padding=10)
        g.pack(fill="x", pady=5)
        ttk.Label(g, text="Каталог:").grid(row=0, column=0, sticky="w")
        ttk.Entry(g, textvariable=self.root_var).grid(row=0, column=1, sticky="ew", padx=8)
        ttk.Button(g, text="Выбрать…", command=self.choose_root).grid(row=0, column=2)
        g.columnconfigure(1, weight=1)

        g = ttk.LabelFrame(frame, text="2. Что включать", padding=10)
        g.pack(fill="x", pady=5)
        left, right = ttk.Frame(g), ttk.Frame(g)
        left.grid(row=0, column=0, sticky="nw", padx=(0, 40))
        right.grid(row=0, column=1, sticky="nw")
        for text, var in [("Полную структуру каталога", self.tree_var), ("Исходный код", self.code_var), ("Конфигурации", self.config_var), ("Обычные текстовые файлы", self.text_var)]:
            ttk.Checkbutton(left, text=text, variable=var).pack(anchor="w", pady=2)
        for text, var in [("README / LICENSE / документацию", self.doc_var), ("Lock-файлы (package-lock и аналоги)", self.output_files_var), ("Включать пустые файлы", self.empty_var)]:
            ttk.Checkbutton(right, text=text, variable=var).pack(anchor="w", pady=2)
        ttk.Label(g, text="Максимальный размер одного файла:").grid(row=1, column=0, sticky="w", pady=(10, 0))
        size = ttk.Frame(g)
        size.grid(row=1, column=1, sticky="w", pady=(10, 0))
        ttk.Spinbox(size, from_=0.1, to=1000, increment=0.5, width=8, textvariable=self.max_var).pack(side="left")
        ttk.Label(size, text="MB").pack(side="left", padx=5)

        g = ttk.LabelFrame(frame, text="3. Фильтр по расширениям (необязательно)", padding=10)
        g.pack(fill="x", pady=5)
        ttk.Label(
            g,
            text="Пусто — фильтр выключен. Иначе: без галочки — попадут только файлы этих "
                 "расширений, с галочкой — наоборот, будут исключены.",
        ).pack(anchor="w")
        row = ttk.Frame(g)
        row.pack(fill="x", pady=(4, 4))
        ttk.Entry(row, textvariable=self.ext_filter_var).pack(side="left", fill="x", expand=True)
        ttk.Checkbutton(
            row, text="Исключать выбранные",
            variable=self.ext_exclude_var,
        ).pack(side="left", padx=(8, 0))
        quick = ttk.Frame(g)
        quick.pack(fill="x")
        ttk.Label(quick, text="Быстро:").pack(side="left")
        for ext in QUICK_EXTENSIONS:
            ttk.Button(
                quick, text=ext, width=6,
                command=lambda e=ext: self.add_ext(e),
            ).pack(side="left", padx=2)
        ttk.Button(
            quick, text="Очистить",
            command=lambda: self.ext_filter_var.set(""),
        ).pack(side="left", padx=(10, 0))

        g = ttk.LabelFrame(frame, text="4. Исключить каталоги", padding=10)
        g.pack(fill="x", pady=5)
        ttk.Entry(g, textvariable=self.exclude_var).pack(fill="x")
        ttk.Label(g, text="Названия через запятую: node_modules, .git, venv, dist …").pack(anchor="w", pady=(4, 0))

        g = ttk.LabelFrame(frame, text="5. Результат", padding=10)
        g.pack(fill="x", pady=5)
        ttk.Label(g, text="TXT:").grid(row=0, column=0, sticky="w")
        ttk.Entry(g, textvariable=self.output_var).grid(row=0, column=1, sticky="ew", padx=8)
        ttk.Button(g, text="Куда сохранить…", command=self.choose_output).grid(row=0, column=2)
        g.columnconfigure(1, weight=1)

        actions = ttk.Frame(frame)
        actions.pack(fill="x", pady=8)
        ttk.Button(actions, text="СОБРАТЬ КОНТЕКСТ", command=self.build).pack(side="left")
        ttk.Button(actions, text="📋 Копировать", command=self.copy).pack(side="left", padx=7)
        ttk.Button(actions, text="💾 Сохранить", command=self.save).pack(side="left")
        ttk.Button(actions, text="📂 Открыть папку", command=self.open_folder).pack(side="left", padx=7)

        ttk.Label(frame, textvariable=self.stats_var).pack(fill="x", pady=(2, 5))
        log_frame = ttk.LabelFrame(frame, text="Журнал", padding=6)
        log_frame.pack(fill="both", expand=True)
        self.log = ScrolledText(log_frame, height=12, wrap="word", font=("Consolas", 9), state="disabled")
        self.log.pack(fill="both", expand=True)
        ttk.Label(frame, textvariable=self.status_var, relief="sunken", anchor="w", padding=5).pack(fill="x", pady=(6, 0))
        self.log_msg("Приложение готово.")

    def log_msg(self, msg: str):
        self.log.configure(state="normal")
        self.log.insert("end", msg + "\n")
        self.log.see("end")
        self.log.configure(state="disabled")
        self.update_idletasks()

    def add_ext(self, ext: str):
        current = self.ext_filter_var.get().strip()
        existing = parse_extensions(current)
        if ext.lower() in existing:
            return
        new = f"{current}, {ext}" if current else ext
        self.ext_filter_var.set(new)

    def choose_root(self):
        selected = filedialog.askdirectory(title="Выберите корневой каталог проекта")
        if selected:
            root = Path(selected).resolve()
            self.root_var.set(str(root))
            self.output_var.set(str(root / f"{root.name}_context.txt"))
            self.status_var.set("Каталог выбран.")
            self.log_msg(f"Выбран проект: {root}")

    def choose_output(self):
        root = Path(self.root_var.get()).expanduser() if self.root_var.get().strip() else Path.home()
        selected = filedialog.asksaveasfilename(
            title="Сохранить контекст проекта", initialdir=str(root if root.exists() else Path.home()),
            initialfile=f"{root.name}_context.txt" if root.name else "project_context.txt",
            defaultextension=".txt", filetypes=[("Text files", "*.txt"), ("All files", "*.*")])
        if selected:
            self.output_var.set(selected)

    def get_settings(self):
        root_text = self.root_var.get().strip()
        if not root_text:
            raise ValueError("Сначала выберите каталог проекта.")
        root = Path(root_text).expanduser().resolve()
        if not root.is_dir():
            raise ValueError("Каталог проекта не существует.")
        try:
            max_mb = float(self.max_var.get().replace(",", "."))
        except ValueError:
            raise ValueError("Максимальный размер файла должен быть числом.")
        if max_mb <= 0:
            raise ValueError("Максимальный размер должен быть больше 0.")
        return root, max_mb

    def build(self):
        try:
            root, max_mb = self.get_settings()
        except ValueError as exc:
            messagebox.showwarning(APP_TITLE, str(exc))
            return
        vars_ = {"tree": self.tree_var, "code": self.code_var, "config": self.config_var,
                 "text": self.text_var, "document": self.doc_var, "output": self.output_files_var,
                 "empty": self.empty_var}
        ignored = parse_exclusions(self.exclude_var.get())
        ext_filter = parse_extensions(self.ext_filter_var.get())
        ext_exclude = self.ext_exclude_var.get()
        self.log_msg("=== СБОРКА ===")
        if ext_filter:
            mode = "исключение" if ext_exclude else "включение"
            self.log_msg(f"Фильтр расширений ({mode}): {', '.join(sorted(ext_filter))}")
        self.log_msg(f"Корень: {root}")
        self.status_var.set("Сканирование проекта…")
        try:
            context, stats = build_context(root, vars_, max_mb, ignored, ext_filter, ext_exclude)
        except Exception as exc:
            self.status_var.set("Ошибка.")
            messagebox.showerror(APP_TITLE, f"Не удалось собрать контекст:\n\n{exc}")
            return
        self.context = context
        if not self.output_var.get().strip():
            self.output_var.set(str(root / f"{root.name}_context.txt"))
        try:
            out = Path(self.output_var.get()).expanduser()
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(context, encoding="utf-8")
        except OSError as exc:
            messagebox.showerror(APP_TITLE, f"Не удалось сохранить TXT:\n\n{exc}")
            return
        self.stats_var.set(
            f"Статистика: элементов {stats['entries']} • файлов {stats['files']} • выбрано {stats['selected']} • включено {stats['included']} • размер {core.format_size(stats['size'])}")
        self.log_msg(f"Выбрано: {stats['selected']}; включено: {stats['included']}; пропущено: {len(stats['skipped'])}")
        self.log_msg(f"Сохранено: {out}")
        self.status_var.set("Готово. Контекст собран.")
        messagebox.showinfo(APP_TITLE, f"Готово!\n\nВключено файлов: {stats['included']}\nРазмер: {core.format_size(stats['size'])}")

    def save(self):
        if not self.context:
            messagebox.showwarning(APP_TITLE, "Сначала соберите контекст.")
            return
        out_text = self.output_var.get().strip()
        if not out_text:
            chosen = filedialog.asksaveasfilename(defaultextension=".txt", filetypes=[("Text files", "*.txt")])
            if not chosen:
                return
            out_text = chosen
            self.output_var.set(chosen)
        try:
            out = Path(out_text).expanduser()
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(self.context, encoding="utf-8")
            self.status_var.set("Файл сохранён.")
            self.log_msg(f"Сохранено: {out}")
        except OSError as exc:
            messagebox.showerror(APP_TITLE, f"Ошибка сохранения:\n\n{exc}")

    def copy(self):
        if not self.context:
            messagebox.showwarning(APP_TITLE, "Сначала соберите контекст.")
            return
        try:
            self.clipboard_clear()
            self.clipboard_append(self.context)
            self.update()
            self.status_var.set("Контекст скопирован в буфер обмена.")
            self.log_msg(f"Скопировано в буфер: {core.format_size(len(self.context.encode('utf-8')))}")
            messagebox.showinfo(APP_TITLE, "Готово!\n\nТеперь можно вставить контекст в ChatGPT через Ctrl+V.")
        except tk.TclError as exc:
            messagebox.showerror(APP_TITLE, f"Ошибка буфера обмена:\n\n{exc}")

    def open_folder(self):
        target = Path(self.output_var.get()).expanduser() if self.output_var.get().strip() else Path.home()
        folder = target.parent if target.suffix else target
        if not folder.exists():
            messagebox.showwarning(APP_TITLE, "Папка ещё не существует.")
            return
        try:
            system = platform.system()
            if system == "Windows":
                os.startfile(str(folder))
            elif system == "Darwin":
                subprocess.run(["open", str(folder)], check=False)
            else:
                subprocess.run(["xdg-open", str(folder)], check=False)
        except Exception as exc:
            messagebox.showerror(APP_TITLE, f"Не удалось открыть папку:\n\n{exc}")


if __name__ == "__main__":
    app = App()
    app.mainloop()
